### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by lingwndr** [eddieantonio/fst-lookup#21]
When I analyze some words, it works perfectly, but for some other words or some inflections of words it throws
`
AssertionError: Arc does not have flags on both labels <fst_lookup.fallback_data.Arc object at 0x7fdfcbc63d40>
`
I'm using a perfectly fine fst which I compiled with Foma and used for many tasks with Foma itself.

**Comment by eddieantonio** [comment]
Could you please provide a minimal example of an FST where this assertion error gets raised? That way, I can test it myself, try to reproduce the bug, and then fix it!

**Comment by lingwndr** [comment]
Thank you for your response.
I use this [Foma FST binary](https://github.com/lingwndr/cpia/raw/master/app/1standard.fst).
and the code is:

`from fst_lookup import FST`
`fst = FST.from_file('1standard.fst')`

for this word it works fine:

`list(fst.analyze('کتاب'))`

but for these two it raises AssertionError:

`list(fst.analyze('رفتم'))`
`list(fst.analyze('برو'))`

**Comment by eddieantonio** [comment]
Thank you for providing the FST. Honestly, it has been a while since I have done anything with FSTs. `fst_lookup` is complaining that it found an arc in the FST where a one side of the label is a flag diacritic and the on the other side is something else. From what I recall working with FSTs four years ago, this is how we always made FSTs or else Bad Things™ would happen. I am not sure if this is a hard requirement when creating FSTs, however, or just an assumption.

I hope to get back to you shortly. The fix might just be to remove the assertion statement :)

**Comment by eddieantonio** [comment]
See near the end here: https://fomafst.github.io/morphtut.html

The tutorial implies that flag diacritics should be aligned on both the lower and upper sides. I have no idea if it's a _hard_ error for flags to be misalligned, as it is in this FST. Either way, I think it's possible to issue a warning during _loading_ rather than issue an error during analysis.

**Comment by eddieantonio** [comment]
There's a new version on pypi that fixes this bug. However, it requires at least Python 3.8: https://pypi.org/project/fst-lookup/

**Comment by dhpour** [comment]
Thanks man, that really helped and saved me a lot of efforts.
